title: InkyNote
description: "Just another ordinary PhD"

url: "https://inkynote.github.io"
baseurl: ""
markdown: kramdown

nav:
  - name: "Home"
    link: "/"
  - name: "PhD Poetry"
    link: "/phd_poetry/"
  - name: "Short Stories"
    link: "/short_stories/"
  - name: "Professional Blog"
    link: "/blog/"
